service: dailywikipediabot

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .vscode/**
    - .env
    - README.md
    - LICENSE
    - package.json
    - package-lock.json
    - requirements.txt

custom:
  appAcronym: dailywikipedia
  dynamodbTable: chats-${self:provider.stage}
  dynamodbArn: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamodbTable}
  dynamodbHost: https://dynamodb.${self:provider.region}.amazonaws.com

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-3'}
  environment:
    BOT_USERMAME: dailywikipediabot
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    DYNAMODB_TABLE: ${self:custom.dynamodbTable}
    DYNAMODB_HOST: ${self:custom.dynamodbHost}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: ${self:custom.dynamodbArn}

functions:
  bot:
    handler: bot.handler
    events:
      - http: POST /
  daily:
    handler: bot.daily
    events:
      - schedule: cron(0 19 * * ? *)

plugins:
  - serverless-python-requirements

resources:
  Resources:
    chatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodbTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1